spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: system
    url: jdbc:mysql://localhost:3306/frontend_backend

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true